# Generated by Django 5.0.3 on 2024-04-02 16:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('short_bio', models.CharField(blank=True, max_length=200, null=True)),
                ('bio', models.CharField(blank=True, max_length=2000, null=True)),
                ('profile_image', models.ImageField(blank=True, default='profiles/default-profile.png', null=True, upload_to='profiles/')),
                ('url_github', models.CharField(blank=True, max_length=200, null=True)),
                ('url_twitter', models.CharField(blank=True, max_length=200, null=True)),
                ('url_linkedin', models.CharField(blank=True, max_length=200, null=True)),
                ('url_website', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id_num', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
