# Generated by Django 5.0.3 on 2024-04-08 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_location_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='url_github',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='url_linkedin',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='url_twitter',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='url_website',
        ),
        migrations.AddField(
            model_name='profile',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
